# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: zh

# avatar image url
head_img: images/avatar.jpg

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: "background-image:url('home.jpg')"

# Particle theme icon is adopts the ant design vue icons
# Link：https://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  home:
    icon:
      name: home
      theme: filled
    src: /hexo-theme-particle-demo/full/public/
  about:
    icon:
      name: idcard
      theme: filled
    src: /hexo-theme-particle-demo/full/public/about
  archives:
    icon:
      name: folder
      theme: filled
    src: /hexo-theme-particle-demo/full/public/archives
  categories:
    icon:
      name: book
      theme: filled
    src: /hexo-theme-particle-demo/full/public/categories
  tags:
    icon:
      name: tags
      theme: filled
    src: /hexo-theme-particle-demo/full/public/tags

# side info card
card:
  enable: true
  description: ["This is description", "can be more lines"]
  icon_links:
    github:
      icon:
        type: antd-icon
        name: github
        theme: filled
        src:
      link: https://github.com/korilin
    twitter:
      icon:
        type: antd-icon
        name: twitter
        theme:
        src:
      link: https://twitter.com/korilin_dev
  friend_links:
    night style: https://korilin.github.io/hexo-theme-particle-demo/night/public
    maiden style: https://korilin.github.io/hexo-theme-particle-demo/maiden/public

# footer info
footer:
  since: 2018
  # Customize the server domain name ICP
  ICP:
    enable: false
    code: 

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo:  # The name of repository of store comments
  owner:  # GitHub repo owner
  admin:  # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: en # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: full
